import { useEffect, useRef, useState } from 'react'
import type { Dispatch, FormEvent, SetStateAction, ReactNode, RefObject } from 'react'
import { auth, db } from './lib/firebase'
import { socket } from './lib/socket'
import { createUserWithEmailAndPassword, onAuthStateChanged, sendPasswordResetEmail, signInWithEmailAndPassword, signOut, updateProfile } from 'firebase/auth'
import { addDoc, collection, doc, getDoc, getDocs, limit, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, arrayUnion } from 'firebase/firestore'

type Lang = 'es'|'en'|'pt'|'fr'|'de'|'it'|'tr'|'ja'|'ko'|'zh'
type Tab = 'home'|'profile'|'friends'|'chat'|'battle'|'ai'|'ranking'|'league'|'clans'|'avatar'|'premium'|'settings'
type AvatarConfig = {skin:string;face:string;hair:string;eyes:string;eyebrows:string;mouth:string;hairColor:string;outfit:string;outfitColor:string;shoes:string;accessory:string;auraColor:string;auraEffect:string;background:string}

type Friend = {id:string; name:string; aura:number}
type ChatMsg = {id:string; uid:string; name:string; text:string; createdAt?:any}
type Clan = {id:string; name:string; tag:string; owner:string; members:string[]; createdAt?:any}

const defaultAvatar: AvatarConfig={skin:'🟤',face:'🙂',hair:'💇',eyes:'👀',eyebrows:'〰️',mouth:'😄',hairColor:'Negro',outfit:'Chaqueta',outfitColor:'Morado',shoes:'👟',accessory:'Ninguno',auraColor:'Violeta',auraEffect:'Pulso',background:'Arena Neon'}
const avatarOptions={skin:['🟤','🟫','🟠','🟡','⚪'],face:['🙂','😎','🥸','🤩','😈'],hair:['💇','🧑‍🎤','👨‍🦱','👩‍🦱','🧑‍🚀','🧑‍🎨'],eyes:['👀','😎','🤓','🧐','🥶'],eyebrows:['〰️','︿','⌁','╱╲'],mouth:['😄','😏','😁','😮','😈'],hairColor:['Negro','Castaño','Rubio','Rojo','Azul','Violeta'],outfit:['Chaqueta','Armadura','Sudadera','Traje','Camiseta','Ninja'],outfitColor:['Morado','Azul','Rojo','Negro','Blanco','Dorado'],shoes:['👟','🥾','👢','🛹'],accessory:['Ninguno','🕶️ Gafas','👑 Corona','🎧 Audífonos','🎩 Sombrero','⚔️ Espada'],auraColor:['Violeta','Azul','Cian','Rojo','Verde','Dorado'],auraEffect:['Pulso','Llamas','Chispas','Energía','Humo','Estrella'],background:['Arena Neon','Ciudad','Espacio','Volcán','Ciberpunk','Oscuro']} as const

const copy:Record<Lang,Record<string,string>>={
 es:{home:'Inicio',profile:'Perfil',friends:'Amigos',chat:'Chat',battle:'Batallas',ai:'IA Aura',ranking:'Ranking',league:'Liga',clans:'Clanes',avatar:'Avatar',premium:'Premium',settings:'Ajustes',welcome:'Prepárate para la batalla',create:'CREAR SALA',join:'UNIRME',code:'CÓDIGO',logout:'Cerrar sesión',login:'Iniciar sesión',register:'Crear cuenta',online:'Jugadores online',play:'JUGAR AHORA'},
 en:{home:'Home',profile:'Profile',friends:'Friends',chat:'Chat',battle:'Battles',ai:'Aura AI',ranking:'Ranking',league:'League',clans:'Clans',avatar:'Avatar',premium:'Premium',settings:'Settings',welcome:'Prepare for battle',create:'CREATE ROOM',join:'JOIN',code:'CODE',logout:'Log out',login:'Log in',register:'Create account',online:'Players online',play:'PLAY NOW'},
 pt:{home:'Início',profile:'Perfil',friends:'Amigos',chat:'Chat',battle:'Batalhas',ai:'IA Aura',ranking:'Ranking',league:'Liga',clans:'Clãs',avatar:'Avatar',premium:'Premium',settings:'Configurações',welcome:'Prepare-se para a batalha',create:'CRIAR SALA',join:'ENTRAR',code:'CÓDIGO',logout:'Sair',login:'Entrar',register:'Criar conta',online:'Jogadores online',play:'JOGAR AGORA'},
 fr:{home:'Accueil',profile:'Profil',friends:'Amis',chat:'Chat',battle:'Combats',ai:'IA Aura',ranking:'Classement',league:'Ligue',clans:'Clans',avatar:'Avatar',premium:'Premium',settings:'Réglages',welcome:'Prépare-toi au combat',create:'CRÉER UNE SALLE',join:'REJOINDRE',code:'CODE',logout:'Déconnexion',login:'Connexion',register:'Créer un compte',online:'Joueurs en ligne',play:'JOUER'},
 de:{home:'Start',profile:'Profil',friends:'Freunde',chat:'Chat',battle:'Kämpfe',ai:'Aura-KI',ranking:'Rangliste',league:'Liga',clans:'Clans',avatar:'Avatar',premium:'Premium',settings:'Einstellungen',welcome:'Bereit für den Kampf',create:'RAUM ERSTELLEN',join:'BEITRETEN',code:'CODE',logout:'Abmelden',login:'Anmelden',register:'Konto erstellen',online:'Spieler online',play:'JETZT SPIELEN'},
 it:{home:'Home',profile:'Profilo',friends:'Amici',chat:'Chat',battle:'Battaglie',ai:'IA Aura',ranking:'Classifica',league:'Lega',clans:'Clan',avatar:'Avatar',premium:'Premium',settings:'Impostazioni',welcome:'Preparati alla battaglia',create:'CREA STANZA',join:'ENTRA',code:'CODICE',logout:'Esci',login:'Accedi',register:'Crea account',online:'Giocatori online',play:'GIOCA ORA'},
 tr:{home:'Ana Sayfa',profile:'Profil',friends:'Arkadaşlar',chat:'Sohbet',battle:'Savaşlar',ai:'Aura Yapay Zeka',ranking:'Sıralama',league:'Lig',clans:'Klanlar',avatar:'Avatar',premium:'Premium',settings:'Ayarlar',welcome:'Savaşa hazırlan',create:'ODA OLUŞTUR',join:'KATIL',code:'KOD',logout:'Çıkış',login:'Giriş',register:'Hesap oluştur',online:'Çevrimiçi',play:'HEMEN OYNA'},
 ja:{home:'ホーム',profile:'プロフィール',friends:'フレンド',chat:'チャット',battle:'バトル',ai:'Aura AI',ranking:'ランキング',league:'リーグ',clans:'クラン',avatar:'アバター',premium:'プレミアム',settings:'設定',welcome:'バトルの準備をしよう',create:'ルーム作成',join:'参加',code:'コード',logout:'ログアウト',login:'ログイン',register:'アカウント作成',online:'オンライン',play:'今すぐプレイ'},
 ko:{home:'홈',profile:'프로필',friends:'친구',chat:'채팅',battle:'배틀',ai:'Aura AI',ranking:'랭킹',league:'리그',clans:'클랜',avatar:'아바타',premium:'프리미엄',settings:'설정',welcome:'배틀을 준비하세요',create:'방 만들기',join:'참가',code:'코드',logout:'로그아웃',login:'로그인',register:'계정 만들기',online:'온라인',play:'지금 플레이'},
 zh:{home:'首页',profile:'资料',friends:'好友',chat:'聊天',battle:'对战',ai:'Aura AI',ranking:'排行榜',league:'联赛',clans:'战队',avatar:'头像',premium:'高级版',settings:'设置',welcome:'准备战斗',create:'创建房间',join:'加入',code:'代码',logout:'退出',login:'登录',register:'创建账号',online:'在线玩家',play:'立即游戏'}
}
const nav:Tab[]=['home','profile','friends','chat','battle','ai','ranking','league','clans','avatar','premium','settings']

export default function App(){
 const [user,setUser]=useState(auth.currentUser); const [authMode,setAuthMode]=useState<'choice'|'login'|'register'>('choice'); const [lang,setLang]=useState<Lang>('es')
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [password2,setPassword2]=useState(''); const [name,setName]=useState(''); const [authMsg,setAuthMsg]=useState('')
 const [tab,setTab]=useState<Tab>('home'); const [profile,setProfile]=useState({aura:0,wins:0,losses:0,level:1}); const [avatar,setAvatar]=useState<AvatarConfig>(defaultAvatar)
 const [friendSearch,setFriendSearch]=useState(''); const [friends,setFriends]=useState<Friend[]>([]); const [friendResults,setFriendResults]=useState<Friend[]>([])
 const [chat,setChat]=useState<ChatMsg[]>([]); const [chatInput,setChatInput]=useState(''); const [chatLoading,setChatLoading]=useState(false)
 const [leaders,setLeaders]=useState<Friend[]>([]); const [clans,setClans]=useState<Clan[]>([]); const [clanName,setClanName]=useState(''); const [clanTag,setClanTag]=useState('')
 const [room,setRoom]=useState(''); const [roomCode,setRoomCode]=useState(''); const [roomStatus,setRoomStatus]=useState('Listo.'); const [opponentJoined,setOpponentJoined]=useState(false); const [host,setHost]=useState(false); const [cameraOn,setCameraOn]=useState(false); const [battleStarted,setBattleStarted]=useState(false); const [aura,setAura]=useState(0); const [opponentAura,setOpponentAura]=useState(0); const [online,setOnline]=useState(0)
 const [premium,setPremium]=useState(false); const [mobileMore,setMobileMore]=useState(false); const [resetSent,setResetSent]=useState(false); const [theme,setTheme]=useState<'neon'|'midnight'>('neon'); const [avatarSaved,setAvatarSaved]=useState(false)
 const videoRef=useRef<HTMLVideoElement>(null); const remoteVideoRef=useRef<HTMLVideoElement>(null); const localStreamRef=useRef<MediaStream|null>(null); const peerRef=useRef<RTCPeerConnection|null>(null); const canvasRef=useRef<HTMLCanvasElement|null>(null)
 const t=copy[lang]

 useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u); if(!u)return; setAuthMode('choice'); const snap=await getDoc(doc(db,'users',u.uid)); if(snap.exists()){const d=snap.data(); setProfile({aura:Number(d.aura||0),wins:Number(d.victorias||0),losses:Number(d.derrotas||0),level:Number(d.level||1)}); if(d.avatar)setAvatar({...defaultAvatar,...d.avatar})} else await setDoc(doc(db,'users',u.uid),{uid:u.uid,nombre:u.displayName||'Jugador',nombreLower:(u.displayName||'Jugador').toLowerCase(),email:u.email||'',aura:0,victorias:0,derrotas:0,level:1,createdAt:serverTimestamp()},{merge:true})}),[])

 useEffect(()=>{ if(!user)return; const q=query(collection(db,'chat'),orderBy('createdAt','desc'),limit(60)); return onSnapshot(q,s=>setChat(s.docs.map(d=>({id:d.id,...d.data()} as ChatMsg)).reverse()),()=>setChatLoading(false)) },[user])
 useEffect(()=>{ if(!user)return; const q=query(collection(db,'users'),orderBy('aura','desc'),limit(25)); return onSnapshot(q,s=>setLeaders(s.docs.map(d=>{const x=d.data(); return {id:d.id,name:x.nombre||'Jugador',aura:Number(x.aura||0)}}))) },[user])
 useEffect(()=>{ if(!user)return; const q=query(collection(db,'clans'),orderBy('createdAt','desc'),limit(20)); return onSnapshot(q,s=>setClans(s.docs.map(d=>({id:d.id,...d.data()} as Clan)))) },[user])
 useEffect(()=>{socket.on('online-count',(n:number)=>setOnline(n)); return()=>{socket.off('online-count')}},[])
 useEffect(()=>{socket.on('peer-joined',()=>{setOpponentJoined(true);setRoomStatus('Rival conectado. ¡Listos para la batalla!')}); socket.on('start',()=>setBattleStarted(true)); socket.on('opponent-aura',(v:number)=>setOpponentAura(Math.round(v))); socket.on('peer-left',()=>{setOpponentJoined(false);setRoomStatus('El rival salió de la sala.')}); socket.on('signal',async(m:any)=>{try{if(!peerRef.current)await preparePeer(); if(m.description){await peerRef.current!.setRemoteDescription(m.description); if(m.description.type==='offer'){const answer=await peerRef.current!.createAnswer();await peerRef.current!.setLocalDescription(answer);socket.emit('signal',{description:peerRef.current!.localDescription})}} if(m.candidate)await peerRef.current!.addIceCandidate(m.candidate)}catch(e){console.warn(e)}}); return()=>{['peer-joined','start','opponent-aura','peer-left','signal'].forEach(x=>socket.off(x))}},[])
 useEffect(()=>{if(!cameraOn||!videoRef.current)return; const v=videoRef.current; const c=canvasRef.current||document.createElement('canvas');canvasRef.current=c;const ctx=c.getContext('2d',{willReadFrequently:true});if(!ctx)return;const timer=window.setInterval(()=>{if(v.readyState<2)return;c.width=64;c.height=48;ctx.drawImage(v,0,0,64,48);const p=ctx.getImageData(0,0,64,48).data;let total=0,bright=0;for(let i=0;i<p.length;i+=4){const x=(p[i]+p[i+1]+p[i+2])/3;total+=x;if(x>155)bright++}const s=Math.min(100,Math.max(0,Math.round(total/(p.length/4)*.42+bright/(p.length/4)*45)));setAura(s);if(battleStarted)socket.emit('aura-score',s)},700);return()=>clearInterval(timer)},[cameraOn,battleStarted])

 async function handleAuth(e:FormEvent){e.preventDefault();setAuthMsg('');try{if(authMode==='register'){if(name.trim().length<2)return setAuthMsg('Escribe un nombre de jugador.');if(password!==password2)return setAuthMsg('Las contraseñas no coinciden.');if(password.length<6)return setAuthMsg('La contraseña debe tener al menos 6 caracteres.');const c=await createUserWithEmailAndPassword(auth,email,password);const clean=name.trim();await updateProfile(c.user,{displayName:clean});await setDoc(doc(db,'users',c.user.uid),{uid:c.user.uid,nombre:clean,nombreLower:clean.toLowerCase(),email,avatar:defaultAvatar,aura:0,victorias:0,derrotas:0,level:1,createdAt:serverTimestamp()},{merge:true})}else await signInWithEmailAndPassword(auth,email,password)}catch(e:any){setAuthMsg(e?.message?.replace('Firebase: Error (auth/','').replace(').','')||'No se pudo completar la operación.')}}
 async function resetPassword(){if(!email.trim()){setAuthMsg('Escribe tu correo para recuperar la contraseña.');return}try{await sendPasswordResetEmail(auth,email.trim());setResetSent(true);setAuthMsg('Te enviamos un enlace para restablecer tu contraseña.')}catch(e:any){setAuthMsg('No pudimos enviar el enlace de recuperación. Revisa el correo.')}}
 async function finishBattle(){if(!user||!battleStarted)return;const win=aura>opponentAura;const delta=win?25:-10;const nextAura=Math.max(0,profile.aura+delta);const nextWins=profile.wins+(win?1:0);const nextLosses=profile.losses+(win?0:1);const nextLevel=Math.max(1,Math.floor(nextAura/100)+1);await updateDoc(doc(db,'users',user.uid),{aura:nextAura,victorias:nextWins,derrotas:nextLosses,level:nextLevel});setProfile({aura:nextAura,wins:nextWins,losses:nextLosses,level:nextLevel});setBattleStarted(false);setRoomStatus(win?'🏆 ¡Victoria! +25 Aura':'⚡ Derrota. -10 Aura')}
 async function logout(){localStreamRef.current?.getTracks().forEach(x=>x.stop());peerRef.current?.close();await signOut(auth);socket.disconnect();setTab('home')}
 async function createRoom(){if(!socket.connected)socket.connect();socket.emit('create',(r:any)=>{if(r?.ok){setRoomCode(r.code);setHost(true);setRoomStatus('Esperando al rival…');setTab('battle')}})}
 function joinRoom(){if(!socket.connected)socket.connect();socket.emit('join',room,(r:any)=>{if(r?.ok){setRoomCode(r.code);setHost(false);setOpponentJoined(true);setRoomStatus('Conectado a la sala.');setTab('battle')}else setRoomStatus(r?.error||'No se pudo unir.')})}
 async function preparePeer(){const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});peerRef.current=pc;localStreamRef.current?.getTracks().forEach(track=>pc.addTrack(track,localStreamRef.current!));pc.onicecandidate=e=>{if(e.candidate)socket.emit('signal',{candidate:e.candidate})};pc.ontrack=e=>{if(remoteVideoRef.current)remoteVideoRef.current.srcObject=e.streams[0]};return pc}
 async function startCamera(){try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:true});localStreamRef.current=s;if(videoRef.current)videoRef.current.srcObject=s;setCameraOn(true);if(!socket.connected)socket.connect();if(!peerRef.current)await preparePeer()}catch{setRoomStatus('Necesitamos permiso para usar la cámara y el micrófono.')}}
 async function startBattle(){if(!opponentJoined||!cameraOn)return;setBattleStarted(true);socket.emit('start');if(host){const pc=peerRef.current||await preparePeer();const offer=await pc.createOffer();await pc.setLocalDescription(offer);socket.emit('signal',{description:pc.localDescription})}}
 async function sendChat(e:FormEvent){e.preventDefault();const text=chatInput.trim();if(!text||!user)return;setChatInput('');try{await addDoc(collection(db,'chat'),{uid:user.uid,name:user.displayName||'Jugador',text,createdAt:serverTimestamp()})}catch{setChat(v=>[...v,{id:crypto.randomUUID(),uid:user.uid,name:user.displayName||'Jugador',text}])}}
 async function searchFriends(){const term=friendSearch.trim().toLowerCase();if(!term)return setFriendResults([]);const snap=await getDocs(query(collection(db,'users'),limit(50)));setFriendResults(snap.docs.filter(d=>d.id!==user?.uid).map(d=>{const x=d.data();return{id:d.id,name:x.nombre||'Jugador',aura:Number(x.aura||0)}}).filter(x=>x.name.toLowerCase().includes(term)).slice(0,10))}
 async function addFriend(f:Friend){if(!user)return;await updateDoc(doc(db,'users',user.uid),{friends:arrayUnion(f.id)});setFriends(v=>v.some(x=>x.id===f.id)?v:[...v,f])}
 async function saveAvatar(){if(!user)return;await updateDoc(doc(db,'users',user.uid),{avatar});localStorage.setItem('auraBattleAvatar',JSON.stringify(avatar));setAvatarSaved(true)}
 async function createClan(){if(!user||clanName.trim().length<3)return;const ref=await addDoc(collection(db,'clans'),{name:clanName.trim(),tag:(clanTag.trim()||'AURA').toUpperCase().slice(0,6),owner:user.uid,members:[user.uid],createdAt:serverTimestamp()});setClanName('');setClanTag('');setTab('clans');alert(`Clan creado: ${ref.id.slice(0,6).toUpperCase()}`)}
 async function joinClan(c:Clan){if(!user)return;await updateDoc(doc(db,'clans',c.id),{members:arrayUnion(user.uid)});alert('Te uniste al clan.')}

 if(!user)return <AuthScreen {...{authMode,setAuthMode,email,setEmail,password,setPassword,password2,setPassword2,name,setName,authMsg,setAuthMsg,handleAuth,resetPassword,resetSent,lang,setLang,t}}/>
 return <div className={`app ${theme}`}><header className="topbar"><div className="brand">⚡ <span>AURA BATTLE</span><b>V4</b></div><div className="top-actions"><span className="online-pill">● {online} {t.online}</span><select value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="es">ES</option><option value="en">EN</option><option value="pt">PT</option><option value="fr">FR</option><option value="de">DE</option><option value="it">IT</option><option value="tr">TR</option><option value="ja">JA</option><option value="ko">KO</option><option value="zh">中文</option></select><button onClick={logout}>{t.logout}</button></div></header>
 <div className="layout"><aside className="sidebar"><div className="mini-profile"><div className="avatar avatar-image"><img src="/assets/avatar-preview.jpg" alt="Avatar"/></div><div><strong>{user.displayName||'Jugador'}</strong><small>⚡ {profile.aura} Aura · Lv.{profile.level}</small></div></div>{nav.map(n=><button key={n} className={tab===n?'nav active':'nav'} onClick={()=>setTab(n)}>{icon(n)} {t[n]}</button>)}<div className="ad-slot side-ad">PUBLICIDAD<br/><small>Espacio para marcas</small></div></aside>
 <main className="content">
 {tab==='home'&&<section className="home-hero"><div className="hero-copy"><div className="eyebrow">⚡ ONLINE AURA ARENA</div><h1>{t.welcome}</h1><p>Compite en vivo, crea tu avatar, gana Aura y construye tu reputación.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab('battle')}>⚔️ {t.play}</button><button onClick={()=>setTab('avatar')}>🧑 Crear mi avatar</button></div><div className="quick-stats"><Stat label="⚡ Tu Aura" value={profile.aura}/><Stat label="🏆 Victorias" value={profile.wins}/><Stat label="🔥 Nivel" value={profile.level}/></div></div><div className="hero-art"><img src="/assets/arena-battle.png" alt="AURA BATTLE Arena"/><div className="hero-glow">LIVE</div></div><div className="home-grid"><Card icon="⚔️" title="Batallas 1v1" text="Crea una sala y reta a otra persona con cámara." action={()=>setTab('battle')}/><Card icon="🤖" title="IA Aura" text="Convierte señales visuales de tu cámara en una métrica de Aura." action={()=>setTab('ai')}/><Card icon="🏆" title="Ranking global" text="Sube posiciones con tus victorias y puntuación." action={()=>setTab('ranking')}/><Card icon="🛡️" title="Clanes" text="Forma equipos y crea una comunidad alrededor de tu Aura." action={()=>setTab('clans')}/></div><div className="ad-slot banner-ad">ESPACIO PUBLICITARIO · AURA BATTLE</div></section>}
 {tab==='profile'&&<Panel title="👤 Mi perfil"><div className="profile-head"><div className="big-avatar avatar-image"><img src="/assets/avatar-preview.jpg" alt="Avatar"/></div><div><h2>{user.displayName||'Jugador'}</h2><p>{user.email}</p><span className="badge">Nivel {profile.level}</span></div></div><div className="stats"><Stat label="Aura" value={profile.aura}/><Stat label="Victorias" value={profile.wins}/><Stat label="Derrotas" value={profile.losses}/><Stat label="Ratio" value={`${profile.wins+profile.losses?Math.round(profile.wins/(profile.wins+profile.losses)*100):0}%`}/></div><div className="profile-actions"><button className="primary" onClick={()=>setTab('avatar')}>🧑 Personalizar avatar</button><button onClick={()=>setTab('settings')}>⚙️ Ajustes</button></div></Panel>}
 {tab==='friends'&&<Panel title="👥 Amigos"><p>Encuentra jugadores y añade rivales a tu red.</p><div className="inline"><input placeholder="Nombre del jugador" value={friendSearch} onChange={e=>setFriendSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&searchFriends()}/><button onClick={searchFriends}>🔎 Buscar</button></div>{friendResults.length>0&&<div className="list">{friendResults.map(f=><div className="list-row" key={f.id}>🧑 <span>{f.name}<small>⚡ {f.aura}</small></span><button onClick={()=>addFriend(f)}>＋ Añadir</button></div>)}</div>}<div className="section-title">Mis amigos</div><div className="list">{friends.length?friends.map(f=><div className="list-row" key={f.id}>🟢 {f.name}<span>⚡ {f.aura}</span></div>):<div className="empty">Todavía no tienes amigos. Busca un jugador arriba.</div>}</div></Panel>}
 {tab==='chat'&&<Panel title="💬 Chat global"><div className="chat-box">{chat.length?chat.map(m=><div className={m.uid===user.uid?'bubble mine':'bubble'} key={m.id}><strong>{m.name}</strong><span>{m.text}</span></div>):<div className="empty">Sé la primera persona en escribir.</div>}</div><form className="inline" onSubmit={sendChat}><input maxLength={300} value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Escribe un mensaje…"/><button className="primary">Enviar</button></form><small className="small">Chat público de la comunidad. No compartas datos personales.</small></Panel>}
 {tab==='battle'&&<Panel title="⚔️ Batallas 1v1"><div className="battle-intro"><div><h2>Entra a la arena</h2><p>Crea una sala y comparte el código con tu rival, o únete a una sala existente.</p></div><div className="live-dot">● LIVE</div></div><div className="room-card">{!roomCode?<div className="room-actions"><button className="primary" onClick={createRoom}>{t.create}</button><span>o</span><input maxLength={6} placeholder={t.code} value={room} onChange={e=>setRoom(e.target.value.toUpperCase())}/><button onClick={joinRoom}>{t.join}</button></div>:<><div className="room-code">{roomCode}</div><button className="copy-btn" onClick={()=>navigator.clipboard?.writeText(roomCode)}>📋 Copiar código</button><div className="status">{roomStatus}</div><div className="battle-actions"><button onClick={startCamera}>📷 {cameraOn?'CÁMARA ACTIVA':'ACTIVAR CÁMARA'}</button><button className="primary" disabled={!opponentJoined||!cameraOn} onClick={startBattle}>🔥 {battleStarted?'BATALLA EN CURSO':'INICIAR BATALLA'}</button>{battleStarted&&<button onClick={finishBattle}>🏁 Terminar y guardar resultado</button>}</div></>}</div><div className="video-grid"><VideoCard title={user.displayName||'Jugador 1'} videoRef={videoRef} score={aura}/><VideoCard title="Rival" videoRef={remoteVideoRef} score={opponentAura}/></div>{battleStarted&&<div className="battle-banner">🔥 BATALLA ACTIVA · ¡Sube tu Aura!</div>}</Panel>}
 {tab==='ai'&&<Panel title="🤖 IA Aura"><div className="ai-hero"><div><h2>Tu Aura actual</h2><div className="aura-number">{aura}</div><p>La lectura actual es un motor visual local de demostración. Más adelante podemos sustituirlo por un modelo ML especializado.</p></div><div className="ai-orb">⚡</div></div><div className="ai-meter"><div className="meter-fill" style={{width:`${aura}%`}}/></div><button className="primary" onClick={startCamera}>{cameraOn?'✓ Cámara conectada':'📷 Activar cámara'}</button><div className="notice">Consejo: buena iluminación y encuadre estable ayudan a obtener una señal visual más consistente.</div></Panel>}
 {tab==='ranking'&&<Panel title="🏆 Ranking global"><div className="podium"><div>🥈 {leaders[1]?.name||'—'}<b>{leaders[1]?.aura||0}</b></div><div>🥇 {leaders[0]?.name||'—'}<b>{leaders[0]?.aura||0}</b></div><div>🥉 {leaders[2]?.name||'—'}<b>{leaders[2]?.aura||0}</b></div></div><div className="leader-list">{leaders.map((x,i)=><div className="leader" key={x.id}><span>#{i+1} · {x.name}</span><b>⚡ {x.aura}</b></div>)}</div></Panel>}
 {tab==='league'&&<Panel title="🥇 Liga"><div className="league-card"><div className="league-badge">⚡</div><h2>Bronce</h2><p>Gana batallas para subir a Plata, Oro y las divisiones superiores.</p><div className="progress"><span style={{width:`${Math.min(100,(profile.wins*10)%101)}%`}}/></div><small>{profile.wins*10} / 100 puntos de ascenso</small></div><div className="three-col"><Stat label="Temporada" value="01"/><Stat label="Victorias" value={profile.wins}/><Stat label="Nivel" value={profile.level}/></div></Panel>}
 {tab==='clans'&&<Panel title="🛡️ Clanes"><div className="clan-create"><input placeholder="Nombre del clan" value={clanName} onChange={e=>setClanName(e.target.value)}/><input maxLength={6} placeholder="TAG" value={clanTag} onChange={e=>setClanTag(e.target.value.toUpperCase())}/><button className="primary" onClick={createClan}>＋ Crear clan</button></div><div className="section-title">Clanes de la comunidad</div><div className="home-grid">{clans.length?clans.map(c=><div className="clan-card" key={c.id}><div className="clan-tag">[{c.tag}]</div><h3>{c.name}</h3><p>👥 {c.members?.length||0} miembros</p><button onClick={()=>joinClan(c)}>Unirme</button></div>):<div className="empty">Sé el primer clan de la comunidad.</div>}</div></Panel>}
 {tab==='avatar'&&<Panel title="🧑 Creador de Avatar"><div className="avatar-builder"><div className={`avatar-preview aura-${avatar.auraColor.toLowerCase()}`}><div className="avatar-bg">{avatar.background==='Espacio'?'🌌':avatar.background==='Volcán'?'🌋':avatar.background==='Ciudad'?'🌃':avatar.background==='Ciberpunk'?'🏙️':avatar.background==='Oscuro'?'🌑':'✨'}</div><div className="avatar-aura">{avatar.auraEffect==='Llamas'?'🔥':avatar.auraEffect==='Chispas'?'⚡':avatar.auraEffect==='Energía'?'💫':avatar.auraEffect==='Humo'?'🌫️':avatar.auraEffect==='Estrella'?'⭐':'✨'}</div><div className="avatar-face"><div className="avatar-hair">{avatar.hair}</div><div className="avatar-eyes">{avatar.eyes}</div><div className="avatar-mouth">{avatar.mouth}</div></div><div className="avatar-body">{avatar.outfit==='Armadura'?'🛡️':avatar.outfit==='Ninja'?'🥷':avatar.outfit==='Traje'?'🤵':'🧥'}<span>{avatar.accessory.startsWith('Ninguno')?'':avatar.accessory.split(' ')[0]}</span></div><div className="avatar-shoes">{avatar.shoes}</div></div><div className="avatar-controls"><div className="builder-title"><div><h2>{user.displayName||'Jugador'}</h2><p>Crea una identidad única para tus batallas.</p></div><button onClick={()=>setAvatar(randomAvatar())}>🎲 Aleatorio</button></div><AvatarGroup title="🎨 Apariencia" fields={[['skin','Piel'],['face','Rostro'],['eyes','Ojos'],['eyebrows','Cejas'],['mouth','Boca'],['hair','Cabello'],['hairColor','Color de cabello']]} avatar={avatar} setAvatar={setAvatar}/><AvatarGroup title="👕 Vestimenta" fields={[['outfit','Ropa'],['outfitColor','Color de ropa'],['shoes','Calzado']]} avatar={avatar} setAvatar={setAvatar}/><AvatarGroup title="✨ Accesorios" fields={[['accessory','Accesorio']]} avatar={avatar} setAvatar={setAvatar}/><AvatarGroup title="⚡ Aura" fields={[['auraColor','Color de Aura'],['auraEffect','Efecto']]} avatar={avatar} setAvatar={setAvatar}/><AvatarGroup title="🌆 Escenario" fields={[['background','Fondo']]} avatar={avatar} setAvatar={setAvatar}/><div className="avatar-save"><button className="primary" onClick={saveAvatar}>💾 GUARDAR AVATAR</button><button onClick={()=>{setAvatar(defaultAvatar);setAvatarSaved(false)}}>↩️ Restablecer</button>{avatarSaved&&<span>✓ Guardado</span>}</div></div></div></Panel>}
 {tab==='premium'&&<Panel title="💎 Premium"><div className="premium-box"><div className="premium-icon">💎</div><h2>AURA BATTLE Premium</h2><p>Beneficios previstos: cosméticos exclusivos, estadísticas avanzadas, insignias y experiencia sin publicidad.</p><div className="premium-list"><span>✓ Avatares y efectos exclusivos</span><span>✓ Estadísticas avanzadas</span><span>✓ Insignia Premium</span><span>✓ Sin publicidad</span></div><button className="primary" onClick={()=>setPremium(v=>!v)}>{premium?'✓ Premium demo activado':'Ver beneficios'}</button></div><div className="notice">Los pagos reales todavía no están activados. Antes de cobrar, conectaremos un proveedor de pagos y políticas legales.</div></Panel>}
 {tab==='settings'&&<Panel title="⚙️ Ajustes"><div className="settings-row"><span>Idioma</span><select value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="es">Español</option><option value="en">English</option><option value="pt">Português</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="it">Italiano</option><option value="tr">Türkçe</option><option value="ja">日本語</option><option value="ko">한국어</option><option value="zh">中文</option></select></div><div className="settings-row"><span>Tema</span><select value={theme} onChange={e=>setTheme(e.target.value as any)}><option value="neon">Neon</option><option value="midnight">Midnight</option></select></div><div className="settings-row"><span>Cuenta</span><button onClick={logout}>Cerrar sesión</button></div><div className="settings-row"><span>Seguridad</span><small>Firebase Authentication activo</small></div><div className="notice">Protege tu contraseña y no compartas códigos privados de salas fuera de la plataforma.</div></Panel>}
 <div className="mobile-bottom-nav">
   {(['home','battle','friends','profile'] as Tab[]).map(n=><button key={n} className={tab===n?'active':''} onClick={()=>{setTab(n);setMobileMore(false)}}><span>{icon(n)}</span><small>{t[n]}</small></button>)}
   <button className={mobileMore?'active':''} onClick={()=>setMobileMore(v=>!v)}><span>☰</span><small>Más</small></button>
 </div>
 {mobileMore&&<div className="mobile-more">{nav.filter(n=>!['home','battle','friends','profile'].includes(n)).map(n=><button key={n} className={tab===n?'active':''} onClick={()=>{setTab(n);setMobileMore(false)}}>{icon(n)} {t[n]}</button>)}</div>}
 </main></div></div>
}

function randomAvatar():AvatarConfig{const a:any={};(Object.keys(avatarOptions) as (keyof AvatarConfig)[]).forEach(k=>a[k]=avatarOptions[k][Math.floor(Math.random()*avatarOptions[k].length)]);return a as AvatarConfig}
function AuthScreen(p:any){const {authMode,setAuthMode,email,setEmail,password,setPassword,password2,setPassword2,name,setName,authMsg,setAuthMsg,handleAuth,resetPassword,resetSent,lang,setLang,t}=p;return <div className="auth-shell"><div className="auth-brand"><div className="brand">⚡ <span>AURA BATTLE</span><b>V4</b></div><p>La arena donde tu Aura habla por ti.</p></div>{authMode==='choice'?<div className="auth-card"><div className="eyebrow">ONLINE AURA ARENA</div><h1>Entra al combate</h1><p>Compite, crea tu avatar y descubre quién domina la arena.</p><button className="primary" onClick={()=>setAuthMode('login')}>🔐 {t.login}</button><button onClick={()=>setAuthMode('register')}>📝 {t.register}</button><div className="lang-line">🌎 <select value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="es">Español</option><option value="en">English</option><option value="pt">Português</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="it">Italiano</option><option value="tr">Türkçe</option><option value="ja">日本語</option><option value="ko">한국어</option><option value="zh">中文</option></select></div></div>:<form className="auth-card" onSubmit={handleAuth}><div className="eyebrow">{authMode==='login'?'ACCESO':'NUEVO JUGADOR'}</div><h1>{authMode==='login'?t.login:t.register}</h1>{authMode==='register'&&<input placeholder="Nombre de jugador" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Correo electrónico" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)} required/>{authMode==='register'&&<><input type="password" placeholder="Repite la contraseña" value={password2} onChange={e=>setPassword2(e.target.value)} required/><div className={password2?(password===password2?'match ok':'match bad'):'match'}>{password2?(password===password2?'✓ Las contraseñas coinciden':'✕ Las contraseñas no coinciden'):'Confirmación de contraseña'}</div></>}{authMsg&&<div className="error">{authMsg}</div>}<button className="primary" type="submit">{authMode==='login'?t.login:t.register}</button>{authMode==='login'&&<button type="button" className="link-button" onClick={resetPassword}>¿Olvidaste tu contraseña?</button>}{resetSent&&<div className="success">✓ Revisa tu correo para restablecerla.</div>}<button type="button" onClick={()=>{setAuthMode('choice');setAuthMsg('')}}>← Volver</button></form>}<div className="ad-slot auth-ad">Espacio publicitario · comunidad AURA BATTLE</div></div>}
function AvatarGroup({title,fields,avatar,setAvatar}:{title:string;fields:Array<[keyof AvatarConfig,string]>;avatar:AvatarConfig;setAvatar:Dispatch<SetStateAction<AvatarConfig>>}){return <div className="avatar-group"><h3>{title}</h3>{fields.map(([key,label])=><div className="avatar-option" key={String(key)}><span>{label}</span><div className="option-list">{(avatarOptions[key] as readonly string[]).map(option=><button type="button" key={option} className={avatar[key]===option?'selected':''} onClick={()=>setAvatar(a=>({...a,[key]:option}))}>{option}</button>)}</div></div>)}</div>}
function icon(n:Tab){return ({home:'🏠',profile:'👤',friends:'👥',chat:'💬',battle:'⚔️',ai:'🤖',ranking:'🏆',league:'🥇',clans:'🛡️',avatar:'🧑',premium:'💎',settings:'⚙️'} as Record<Tab,string>)[n]}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="panel"><div className="panel-title">{title}</div>{children}</section>}
function Card({icon,title,text,action}:{icon:string;title:string;text:string;action:()=>void}){return <button className="feature" onClick={action}><span>{icon}</span><div><h3>{title}</h3><p>{text}</p></div><b>→</b></button>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="stat"><small>{label}</small><strong>{value}</strong></div>}
function VideoCard({title,videoRef,score}:{title:string;videoRef:RefObject<HTMLVideoElement|null>;score:number}){return <div className="video-card"><h3>{title}</h3><div className="video-frame"><video ref={videoRef} autoPlay playsInline muted={title!=='Rival'}/></div><div className="score-line"><b>⚡ {score}</b><div className="bar"><span style={{width:`${Math.min(100,score)}%`}}/></div></div></div>}
